config/routes.rb
Rails.application.routes.draw do
  get 'financeiro/index'
  get 'financeiro/atendimento_valor'
  get 'financeiro/recebimento_pessoa'
  get 'financeiro/repasse_profissionais'

  # usuarios do sistema e sessão
  resources :usuarios
  resources :sessoes
  get 'criar_usuario', to: "usuarios#new", as: 'criar_usuario'
  get 'entrar', to: "sessoes#new", as: 'entrar'
  get 'sair', to: "sessoes#destroy", as: 'sair'

  # instrumentos
  resources :instrumentos
  resources :instrumento_relatos

  # anamneses
  resources :infantojuvenil_anamneses

  # biblioteca
  resources :biblioteca_obras
  resources :biblioteca_autores
  resources :biblioteca_tags
  
  scope :financeiro do
    resources :atendimento_valores
    resources :recebimentos
  end

  resources :profissionais do
    member do
      get :acompanhamentos
    end
  end
  resources :pessoa_devolutivas
  resources :laudos
  resources :crp_regioes
  resources :profissional_notas
  #resources :pessoas
  resources :pessoas, path: '/cadastros' do
    member do
      get :devolutivas, path: 'devolutivas'
      get :responsavel_devolutivas
      get :informacoes_extras
      get :informacao_extra_new, path: "informacoes_extras/new"
      get :informacao_extra_edit, path: "informacoes_extras/:extra_info_id"
    end
  end
  resources :paises
  resources :continentes
  resources :acompanhamentos do
    post :new_atendimento_proxima_semana, path: 'novo_atendimento_proxima_semana'
  end
  resources :atendimentos do
    member do
      post :reagendar_para_proxima_semana
      get :reagendar_para_proxima_semana
      post :create_atendimento_valor
    end
  end
  resources :relatos
  resources :pessoa_extra_informacoes

  resources :profissional_documento_modelos

  root to: "application#index"
  get '/financeiro', to: "financeiro#index"

  scope :admin do
    get '/', to: "admin#index", as: 'admin'
    AdminController.paths.each do |m|
      resources m.to_sym
      #get m.to_sym, to: "admin##{m}", as: m.to_s
    end
  end

  # rotas pdf
  get "/acompanhamentos/:id/detalhes", to: "acompanhamentos#caso_detalhes"
  get "/relatos/:id/pdf", to: "relatos#show_pdf"
  get "/pessoa_extra_informacoes/:id/pdf", to: "pessoa_extra_informacoes#show_pdf"

  # get pdf
  get "/pdf_download", to: "application#pdf_download"
  get "/pdf_preview", to: "application#pdf_preview"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recebimento.rb
class Recebimento < ApplicationRecord
  require "csv"

  scope :do_mes_passado, -> { where(data: (Date.today - 1.month).all_month) }
  scope :do_mes_atual, -> { where(data: Date.today.all_month) }
  scope :deste_mes, -> { do_mes_atual }
  scope :do_ano_atual, -> { where(data: Date.today.all_year) }
  scope :deste_ano, -> { do_ano_atual }
  scope :do_ano_passado, -> { where(data: (Date.today - 1.year).all_year) }

  scope :do_periodo, -> (mes: Date.today.month, ano: Date.today.year, ordem: :desc) { where("YEAR(data) = #{ano} AND MONTH(data) = #{mes}").order(data: ordem) }

  belongs_to :acompanhamento

  has_one :pessoa, through: :acompanhamento
  belongs_to :pessoa_pagante, class_name: "Pessoa", foreign_key: :pessoa_pagante_id, optional: true
  has_one :profissional, through: :acompanhamento
  #belongs_to :profissional

  belongs_to :recebimento_modalidade, foreign_key: :modalidade_id, class_name: "PagamentoModalidade"

  def pagante
    pessoa_pagante || pessoa
  end

  def beneficiario
    pessoa
  end

  def profissional
    acompanhamento.profissional
  end

  def modalidade
    recebimento_modalidade.modalidade
  end

  def servico_prestado
    acompanhamento.tipo
  end

  def para_linha_csv
    "#{pagante.nome_completo},#{pagante.cpf},#{beneficiario.nome_completo},#{beneficiario.cpf},#{data},#{modalidade},#{valor},#{acompanhamento.acompanhamento_tipo.tipo}" + "\n"
  end

  def self.para_csv(collection = all, formato_data: "%Y-%m-%d")
    CSV.generate(col_sep: ',') do |csv|
      csv << [
        "DATA",
        "VALOR",
        "BENEFICIÁRIO",
        "CPF BENEFICIÁRIO",
        "PAGANTE",
        "CPF PAGANTE",
        "PROFISSIONAL",
        "REGISTRO PROFISSIONAL",
        "CPF PROFISSIONAL",
        "CIDADE PROFISSIONAL",
        "SERVIÇO PRESTADO",
        "MODALIDADE DE PAGAMENTO"
      ]
      collection.each do |r|
        csv << [
          r.data.strftime(formato_data),
          r.valor.to_s,
          r.beneficiario.nome_completo,
          r.beneficiario.cpf,
          r.pagante.nome_completo,
          r.pagante.cpf,
          r.profissional.nome_completo,
          r.profissional.documento,
          r.profissional.pessoa.cpf,
          r.profissional.pessoa.cidade,
          r.servico_prestado,
          r.modalidade
        ]
      end
    end
  end
end

app/controllers/recebimentos_controller.rb
class RecebimentosController < ApplicationController
  require 'csv'

  before_action :set_recebimento, only: %i[ show update edit delete recibo ]
  before_action :validar_usuario#, only: %i[ show update edit delete recibo ]

  def index
    @ano = params[:ano] || Date.today.year
    @mes = params[:mes] || Date.today.month
    @ano_mes = "#{@ano}-#{@mes.to_s.rjust(2, "0")}"
    #@recebimentos = nil
    if usuario_atual.financeiro?
      @pessoas = Pessoa.joins(:atendimento_valores).distinct.order(nome: :asc, sobrenome: :asc)
      @atendimento_valores = AtendimentoValor.joins(:atendimento).where("atendimentos.data" => "#{@ano_mes}-01".."#{@ano_mes}-01".to_date.end_of_month.to_s)
      @recebimentos = Recebimento.do_periodo(mes: @mes, ano: @ano)
    else
      @pessoas = usuario_atual.profissional.pacientes
      @atendimento_valores = usuario_atual.profissional.atendimento_valores.joins(:atendimento).where("atendimentos.data" => "#{@ano_mes}-01".."#{@ano_mes}-01".to_date.end_of_month.to_s)
      @recebimentos = usuario_atual.profissional.recebimentos.do_periodo(mes: @mes, ano: @ano)
    end
    respond_to do |format|
      format.html
      format.csv do
        send_data Recebimento.para_csv(@recebimentos), filename: "#{Rails.application.class.module_parent_name.to_s}-relatorio-recebimentos_#{@ano}-#{ @mes.to_s.rjust(2, "0")}.csv", type: 'text/csv'
      end
      format.xlsx do
        response.headers['Content-Disposition'] = "attachment; filename=#{Rails.application.class.module_parent_name.to_s}-relatorio-recebimentos_#{@ano}-#{@mes.to_s.rjust(2, "0")}.xlsx"
      end
    end
  end

  def show
  end

  def new
    @recebimento = Recebimento.new
  end

  def edit
  end

  def create
    if !usuario_atual.financeiro?
      if !usuario_atual.profissional.acompanhamentos.map(&:id).include?(params[:recebimento][:acompanhamento_id])
        render file: "#{Rails.root}/public/404.html", status: 403
        return
      end
    end
    @recebimento = Recebimento.new(recebimento_params)
    if params[:recebimento][:direto_profissional]
      p = params[:recebimento]
      ProfissionalFinanceiroRepasse.create(profissional_id: Acompanhamento.find(p[:acompanhamento_id]).profissional.id, valor: p[:valor], data: p[:data], modalidade_id: p[:modalidade_id])
    end

    respond_to do |format|
      if @recebimento.save
        format.html { redirect_to recebimentos_path, notice: "recebimento was successfully created." }
        format.json { render :index, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recebimento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if !usuario_atual.financeiro?
      if !usuario_atual.profissional.acompanhamentos.map(&:id).include?(params[:recebimento][:acompanhamento_id])
        render file: "#{Rails.root}/public/404.html", status: 403
        return
      end
    end
    respond_to do |format|
      if @recebimento.update(recebimento_params)
        format.html { redirect_to recebimentos_path, notice: "recebimento was successfully updated." }
        format.json { render :index, status: :ok}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recebimento.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end

  def recibo
    hoje = Time.now.strftime("%Y-%m-%d")
    hoje_formatado = Time.now.strftime("%d/%m/%Y")
    nome_documento = "Recibo_#{hoje}"
  end

  private

  def set_recebimento
    @recebimento = Recebimento.find(params[:id])
  end

  def recebimento_params
    params.require(:recebimento).permit(:pessoa_pagante_id, :acompanhamento_id, :valor, :data, :modalidade_id)
  end

  def validar_usuario
    if usuario_atual.nil? || !(usuario_atual.corpo_clinico? || usuario_atual.financeiro?)
      render file: "#{Rails.root}/public/404.html", status: 403
    end
  end
end

app/helpers/recebimentos_helper.rb
module RecebimentosHelper
end

app/views/recebimentos/_card.html.erb
<%= link_to edit_recebimento_path(recebimento) do %>
  <div class="recebimento-card">
    <h2>
      <%= recebimento.acompanhamento.render_info_para_profissional %>
      (<%= recebimento.modalidade %>)
    </h2>
    <h3><%= if !recebimento.pagante.nil? then " (pago por #{recebimento.pagante.nome_abreviado})" end %></h3>
    <p><strong><%= render_dinheiro_centavos recebimento.valor %></strong></p>
    <p><%= render_data_brasil recebimento.data %></p>
    <p><%= recebimento.profissional.nome_abreviado %> <span style="font-size:.7em;"><%= recebimento.profissional.documento %></span></p>
  </div>
<% end %>

app/views/recebimentos/_form.html.erb
<div class="recebimento-form">
  <% if recebimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recebimento.errors.count, "error") %> prohibited this recebimento from being saved:</h2>

      <ul>
      <% recebimento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: recebimento, local: true) do |form| %>

    <div class="field">
      <% acompanhamentos = usuario_atual.financeiro? ? Acompanhamento.all.order(data_inicio: :asc) : usuario_atual.profissional.acompanhamentos.order(data_inicio: :asc) %>
      <%= form.label "Acompanhamento" %>
      <%= form.select :acompanhamento_id, acompanhamentos.map { |a| [a.render_info_padrao, a.id] } %>
    </div>

    <div class="field">
      <%= form.label "Pagante" %>
      <%= form.select :pessoa_pagante_id, Pessoa.all.order(nome: :asc, sobrenome: :asc).map { |pessoa| [pessoa.nome_completo, pessoa.id] }, include_blank: true %>
    </div>

    <div class="field">
      <%= form.label "Valor" %>
      <%= form.number_field :valor %>
    </div>

    <div class="field">
      <%= form.label "Data do pagamento" %>
      <%= form.date_field :data %>
    </div>

    <div class="field">
      <%= form.label "Modalidade de pagamento" %>
      <%= form.select :modalidade_id, PagamentoModalidade.all.map { |mod| [mod.modalidade, mod.id] } %>
    </div>

    <div class="field">
      <%= form.label "Direto para o profissional" %>
      <%= form.check_box :direto_profissional %>
    </div>

    <div class="action">
      <%= form.submit %>
    </div>

  <% end %>
</div>

app/views/recebimentos/create.html.erb
<h1>Recebimentos#create</h1>
<p>Find me in app/views/recebimentos/create.html.erb</p>

app/views/recebimentos/delete.html.erb
<h1>Recebimentos#delete</h1>
<p>Find me in app/views/recebimentos/delete.html.erb</p>

app/views/recebimentos/edit.html.erb
<h1>Editar recebimento</h1>
<%= render 'form', recebimento: @recebimento %>

app/views/recebimentos/index.html.erb
<%= titulo "Recebimentos #{t('date.month_names')[@mes.to_i]} #{@ano}" %>

<h1>Recebimentos - <%= t('date.month_names')[@mes.to_i] %>/<%= @ano %></h1>

<div class="form-g">
  <%= form_with url: recebimentos_path, method: :get, local: true do |f| %>
    <%#= f.label :mes, "Selecionar mês" %>
    <%= f.select :mes, 
        [1,2,3,4,5,6,7,8,9,10,11,12].map { |i| [t('date.month_names')[i], i] },
        selected: @mes %>
    /
    <%#= f.label :ano, "Selecionar ano" %>
    <% anos = [] %>
    <% ano_atual = Date.today.year %>
    <% while ano_atual != Recebimento.minimum(:data).year - 1 do %>
      <% anos << ano_atual %>
      <% ano_atual -= 1 %>
    <% end %>
    <%= f.select :ano, anos, selected: @ano %>

    <%= f.submit "Atualizar" %>
  <% end %>
</div>

<p>Baixar relatório
<%= link_to "CSV", recebimentos_path(format: :csv, ano: @ano, mes: @mes) %>
<%= link_to "Excel", recebimentos_path(format: :xlsx, ano: @ano, mes: @mes) %>
</p>
<%= link_to "+ recebimento", new_recebimento_path, { class: "btn-dinheiro" } %>
<p>
  Recebimentos do mês:
  <% @total_mes = @recebimentos.sum(:valor) %>
  <%= render_dinheiro_centavos @total_mes %>
</p>

<div class="valores-cobrar-container">
  <div class="valores-cobrar">
    <h3>Valores a cobrar até mês passado</h3>
    <% @a_receber = 0 %>
    <% @pessoas.each do |pessoa| %>
      <% a_receber_ate_mes_passado = pessoa.atendimento_valores.where("atendimentos.data" => [..(Date.today - 1.month).end_of_month]).sum("valor - desconto") %>
      <% ja_recebidos = pessoa.recebimentos.sum(:valor) %>
      <% resultado = a_receber_ate_mes_passado - ja_recebidos %>

      <% if resultado > 0 %>
        <div class="pessoa-devendo">
          <%= pessoa.nome_abreviado %>
          <%= render_dinheiro_centavos resultado %>
          <% @a_receber += resultado %> 
        </div>
      <% end %>
    <% end %>
    <p><strong>Total a receber: <%= render_dinheiro_centavos @a_receber %></strong></p>
  </div>

  <div class="valores-cobrar">
    <h3>Valores pendentes este mês</h3>
    <% @a_receber_mes_atual = 0 %>
    <% @pessoas.each do |pessoa| %>
      <% ja_recebidos = pessoa.recebimentos.sum(:valor) %>
      <% resultado = pessoa.atendimento_valores.where(atendimentos: {data: [..Date.today]}).sum("valor - desconto") - ja_recebidos %>
      <% if resultado > 0 %>
        <% @a_receber_mes_atual += resultado %>
        <div class="pessoa-devendo">
          <%= pessoa.nome_abreviado %>: <%= render_dinheiro_centavos resultado %>
        </div>
      <% end %>
    <% end %>
    <strong>Total a receber: <%= render_dinheiro_centavos @a_receber_mes_atual %></strong><br />
    <strong>Valor de atendimentos deste mês: <%= render_dinheiro_centavos @atendimento_valores.sum("valor - desconto") %></strong>
  </div>
</div>

<div class="valores-pagos">
  <% @recebimentos.each do |recebimento| %>

  <% end %>
</div>

<table class="tabela-recebimentos">
  <caption>Recebimentos - <%= t('date.month_names')[@mes.to_i] %>/<%= @ano %></caption>
  <thead>
    <tr>
      <th>Beneficiário</th>
      <th>Pagante</th>
      <th>Data</th>
      <th>Valor</th>
      <th>Profissional</th>
      <th>Serviço</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <% @recebimentos.each do |recebimento| %>
      <tr>
        <td><%= recebimento.beneficiario.nome_abreviado %></td>
        <td><%= recebimento.pagante.nome_abreviado %></td>
        <td style="text-align:center;"><%= render_data_brasil recebimento.data %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos recebimento.valor %></td>
        <td style="text-align:center;"><%= recebimento.profissional.descricao_completa %></td>
        <td style="text-align:center;"><%= recebimento.acompanhamento.tipo.upcase %></td>
        <td style="text-align:center;"><%= link_to "Editar", edit_recebimento_url(recebimento) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recebimentos/new.html.erb
<%= titulo "Novo recebimento" %>
<h1>Registrar recebimento</h1>

<%= render 'form', recebimento: @recebimento %>

app/views/recebimentos/show.html.erb
<h1>Recebimentos#show</h1>
<p>Find me in app/views/recebimentos/show.html.erb</p>

app/views/recebimentos/update.html.erb
<h1>Recebimentos#update</h1>
<p>Find me in app/views/recebimentos/update.html.erb</p>