config/routes.rb
Rails.application.routes.draw do
  get 'financeiro/index'
  get 'financeiro/atendimento_valor'
  get 'financeiro/recebimento_pessoa'
  get 'financeiro/repasse_profissionais'

  # usuarios do sistema e sessão
  resources :usuarios
  resources :sessoes
  get 'criar_usuario', to: "usuarios#new", as: 'criar_usuario'
  get 'entrar', to: "sessoes#new", as: 'entrar'
  get 'sair', to: "sessoes#destroy", as: 'sair'

  # instrumentos
  resources :instrumentos
  resources :instrumento_relatos

  # anamneses
  resources :infantojuvenil_anamneses

  # biblioteca
  resources :biblioteca_obras
  resources :biblioteca_autores
  resources :biblioteca_tags
  
  scope :financeiro do
    resources :atendimento_valores
    resources :recebimentos
  end

  resources :profissionais do
    member do
      get :acompanhamentos
    end
  end
  resources :pessoa_devolutivas
  resources :laudos
  resources :crp_regioes
  resources :profissional_notas
  #resources :pessoas
  resources :pessoas, path: '/cadastros' do
    member do
      get :devolutivas, path: 'devolutivas'
      get :responsavel_devolutivas
      get :informacoes_extras
      get :informacao_extra_new, path: "informacoes_extras/new"
      get :informacao_extra_edit, path: "informacoes_extras/:extra_info_id"
    end
  end
  resources :paises
  resources :continentes
  resources :acompanhamentos do
    post :new_atendimento_proxima_semana, path: 'novo_atendimento_proxima_semana'
  end
  resources :atendimentos do
    member do
      post :reagendar_para_proxima_semana
      get :reagendar_para_proxima_semana
      post :create_atendimento_valor
    end
  end
  resources :relatos
  resources :pessoa_extra_informacoes

  resources :profissional_documento_modelos

  root to: "application#index"
  get '/financeiro', to: "financeiro#index"

  scope :admin do
    get '/', to: "admin#index", as: 'admin'
    AdminController.paths.each do |m|
      resources m.to_sym
      #get m.to_sym, to: "admin##{m}", as: m.to_s
    end
  end

  # rotas pdf
  get "/acompanhamentos/:id/detalhes", to: "acompanhamentos#caso_detalhes"
  get "/relatos/:id/pdf", to: "relatos#show_pdf"
  get "/pessoa_extra_informacoes/:id/pdf", to: "pessoa_extra_informacoes#show_pdf"

  # get pdf
  get "/pdf_download", to: "application#pdf_download"
  get "/pdf_preview", to: "application#pdf_preview"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  belongs_to :civil_estado, optional: true
  belongs_to :instrucao_grau, optional: true
  belongs_to :pais, optional: true
  belongs_to :pessoa_tratamento_pronome, optional: true
  
  # has associations
  has_one :usuario
  # quando o cadastro for de um profissional
  has_one :profissional
  has_many :profissional_acompanhamento, through: :profissional, source: :acompanhamento

  # quando o cadastro for de um paciente
  has_many :acompanhamentos
  has_many :atendimentos, through: :acompanhamentos
  has_many :instrumento_relatos, through: :atendimentos
  has_many :instrumentos_aplicados, through: :instrumento_relatos, source: :instrumento
  has_many :profissionais_acompanhando, class_name: "Profissional", through: :acompanhamento, source: :profissional
  has_many :devolutivas, class_name: "PessoaDevolutiva", foreign_key: :pessoa_id
  has_many :laudos, through: :acompanhamentos
  # quando o cadastro for de um resopnsável
  has_many :acompanhamentos_responsavel, class_name: "Acompanhamento", foreign_key: :pessoa_responsavel_id
  has_many :profissionais_a_quem_responde, class_name: "Profissional", through: :acompanhamento_responsavel, source: :profissional
  has_many :responsavel_devolutivas, class_name: "PessoaDevolutiva", foreign_key: :pessoa_responsavel_id

  has_many :recebimentos, through: :acompanhamentos
  has_many :recebimentos_pagante, class_name: "Recebimento", foreign_key: :pessoa_pagante_id

  #has_many :recebimento_beneficiario_old, class_name: "Recebimento", foreign_key: :pessoa_beneficiario_id

  has_many :atendimento_valores, through: :atendimentos

  has_many :pessoa_extra_informacao



  def nome_completo
    if !nome_do_meio.nil?
      [nome, nome_do_meio, sobrenome].join(' ')
    else
      [nome, sobrenome].join(' ')
    end
  end

  def nome_abreviado_meio
    #nome_abrev = (nome + ' ' + nome_do_meio).split.map { |n| n[0] == n[0].upcase ? n[0] : '' }
    #nome_abrev = abreviar(nome + ' ' + nome_do_meio, '. ')
    #[nome_abrev.reject(&:empty?) || nome_abrev, sobrenome].join('. ')
    if nome_do_meio
      abreviar(nome + ' ' + nome_do_meio.to_s, '. ') + '. ' + sobrenome
    else
      abreviar(nome, '. ') + '. ' + sobrenome
    end
  end

  def nome_abreviado
    if nome_do_meio
      meio_abrev = nome_do_meio.to_s.split.map { |n| n[0] == n[0].upcase ? n[0] : '' }
      meio_sobrenome = [meio_abrev.reject(&:empty?) || meio_abrev, sobrenome].join(". ")
      [nome, meio_sobrenome].join(' ')
      nome + ' ' + [abreviar(nome_do_meio, '. '), sobrenome].join('. ')
    else
      nome + ' ' + sobrenome
    end
  end

  def nome_sigla
    abreviar([nome, nome_do_meio, sobrenome].join(' '))
  end

  def nome_e_sobrenome
    nome + ' ' + sobrenome
  end

  def render_cpf
    cr = cpf.to_s
    # padding zeros
    cr = ("00000000000" + cr).delete(" ").chars.last(11).join("").to_s
    cr.at(0..2) + "." + cr.at(3..5) + "." + cr.at(6..8) + "-" + cr.at(-2..) 
  end

  def tem_telefone?
    fone_cod_area && fone_num && fone_cod_pais
  end
  
  def render_fone
    tem_telefone? ?
      fr = "+" + fone_cod_pais + " (" + fone_cod_area + ") " + fone_num[..-5] + "-" + fone_num[-4..]
    :
      nil
  end

  def render_fone_link
    tem_telefone? ? "#{fone_cod_area}#{fone_num}" : nil
  end


  def render_data_nascimento
    data_nascimento.strftime("%d/%m/%Y")
  end

  def render_idade(data = Time.now.to_date)
    if data_nascimento == nil then return "idade não informada" end
    hoje = data
    #hoje = Date.parse '1996-11-07'


    hoje_ano = hoje.year
    hoje_mes = hoje.month
    hoje_dia = hoje.day

    nasc_ano = data_nascimento.year
    nasc_mes = data_nascimento.month
    nasc_dia = data_nascimento.day

    # agora para os calculos
    dia_dif = hoje_dia - nasc_dia
    mes_dif = hoje_mes - nasc_mes
    ano_dif = hoje_ano - nasc_ano

    #return "#{dia_dif} #{mes_dif} #{ano_dif}"

    # nascido no mesmo ano que hoje
    if ano_dif == 0
      plural = mes_dif == 1 ? "mês" : "meses"
      return "#{hoje_mes - nasc_mes} #{plural}"
    end

    # nascido no mesmo mês que hoje
    if mes_dif == 0
      dia_me = dia_dif >= 0
      anos_idade = dia_me ? ano_dif : ano_dif - 1
      plural_anos = anos_idade == 1 ? "" : "s"
      tem_meses = !dia_me ? " e 11 meses" : ""
      return "#{anos_idade} ano#{plural_anos}#{tem_meses}"
    end

    # agora o bicho vai pegar
    meses_idade = mes_dif < 0 ? 12 + mes_dif : mes_dif
    dias_idade = dia_dif >= 0
    meses_idade = dias_idade ? meses_idade : meses_idade - 1
    anos_idade = mes_dif > 0 ? ano_dif : ano_dif - 1

    plural_anos = anos_idade == 1 ? "ano" : "anos"
    plural_meses = meses_idade == 1 ? "mês" : "meses"
    tem_meses = meses_idade > 0 ? " e #{meses_idade} #{plural_meses}" : ""

    return "#{anos_idade} #{plural_anos}#{tem_meses}"

    return "Não foi possível calcular idade"
  end


  def render_sexo
    if feminino then "Feminino" else "Masculino" end
  end

  def render_sexo_sigla
    if feminino then "(F)" else "(M)" end
  end

  def estado_civil
    sufixo = feminino ? 'a' : 'o'
    civil_estado.estado[..-2] + sufixo
  end

  def render_cep
    if endereco_cep == nil then return nil end
    if pais.nome = "Brasil" then return endereco_cep.to_s[0..-3] + '-' + endereco_cep.to_s[-3..] end
  end

  def render_endereco
    if endereco_logradouro == nil then return "Endereço não informado" end
    num = endereco_numero || "Sem número"
    complemento = endereco_complemento || ""
    cpostal = render_cep || "Código postal não informado"
    "#{endereco_logradouro} #{num} #{endereco_complemento} - #{cpostal}"
  end

  def render_cidade_estado
    c = cidade || "Não informado"
    e = estado || "Não informado"
    "#{c} - #{e}"
  end

  def nome_relato
    "#{nome[-2..].upcase}#{sobrenome[..2].upcase}#{nome[..1].upcase}"
  end

  def informacoes_extras
    pessoa_extra_informacao
  end

  def atendimentos_futuros
    atendimentos.where("DATEDIFF(data, CURRENT_DATE) > 0 OR (DATEDIFF(data, CURRENT_DATE) = 0 AND HOUR(horario) > HOUR(CURRENT_TIME))")
  end

  def recebimentos_beneficiario
    recebimentos
  end

  def valor_a_cobrar_ate_mes_passado
    atendimento_valores.where(atendimentos: {data: [..(Date.today - 1.month).end_of_month]}).sum("valor - desconto") - recebimentos.sum(:valor)
  end

  def pronome_tratamento
    pronome_no_feminino = (feminino && !inverter_pronome_tratamento) || (!feminino && inverter_pronome_tratamento)
    pronome_no_feminino ? pessoa_tratamento_pronome.pronome_feminino : pessoa_tratamento_pronome.pronome_masculino
  end

  def pronome_tratamento_abreviado
  end

  private

  def abreviar string, separator = ''
    string = string.to_s
    str_abreviar = string.split.map { |n| n[0] == n[0].upcase ? n[0] : ''}
    str_abreviar = str_abreviar.reject!(&:empty?) || str_abreviar
    str_abreviar.join(separator)
  end


  # recebimentos
  def valor_a_cobrar
    atendimento_valores.sum("valor - desconto") - recebimento.sum(:valor)
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: %i[ show edit update destroy devolutivas informacoes_extras informacao_extra_edit informacao_extra_new ]
  before_action :validar_usuario#, only: %i[ show edit update destroy devolutivas informacoes_extras informacao_extra_edit informacao_extra_new ]
  include Pagy::Backend

  # GET /pessoas or /pessoas.json
  def index
    if params[:q].present?
      @pessoas = Pessoa.where("LOWER(CONCAT(nome, ' ', COALESCE(nome_do_meio, ''), ' ', sobrenome)) LIKE ?", "%#{params[:q].to_s.downcase}%")
    else
      @pessoas = Pessoa.all.order(nome: :asc, nome_do_meio: :asc, sobrenome: :asc)
    end
    @pagy, @pessoas = pagy(@pessoas, items: 10)
  end

  # GET /pessoas/1 or /pessoas/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        nome_documento = "Ficha-de-cadastro_#{@pessoa.nome_completo.parameterize}"
        pdf = PessoaPdf.new(@pessoa)
        send_data pdf.render,
          filename: "#{nome_documento}.pdf",
          type: "application/pdf",
          disposition: :inline
      end
    end
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas or /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to pessoa_url(@pessoa), notice: "Pessoa was successfully created." }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1 or /pessoas/1.json
  def update
    params["pessoa"]["cpf"] = params["pessoa"]["cpf"].gsub(/\D/, '')[-11..]
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to pessoa_url(@pessoa), notice: "Pessoa was successfully updated." }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1 or /pessoas/1.json
  def destroy
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: "Pessoa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def informacoes_extras
    @extra_informacoes = @pessoa.pessoa_extra_informacao.order(data: :asc)
  end

  def informacao_extra_edit
    @extra_informacao = PessoaExtraInformacao.find(params[:extra_info_id])
  end

  def informacao_extra_update
    @extra_informacao.update(pessoa_extra_informacao_params)
  end

  def informacao_extra_new
    @extra_informacao = @pessoa.pessoa_extra_informacao.new
  end

  def informacao_extra_create
  end

  ### recursos extras
  # devolutivas
  def devolutivas
    @devolutivas = @pessoa.devolutiva.order(data: :desc)
    respond_to do |format|
      format.html
      format.json
      format.js
      format.pdf
    end
  end
  def responsavel_devolutivas
    @devolutivas = @pessoa.responsavel_devolutiva.order(data: :desc)
    respond_to do |format|
      format.html
      format.json
      format.js
      format.pdf
    end
  end

  # pdfs
  
  def pdf_ficha

  end


  def pdf_info_extra
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :nome_do_meio, :sobrenome, :cpf, :fone_cod_pais, :fone_cod_area, :fone_num, :feminino, :civil_estado_id, :instrucao_grau_id, :data_nascimento, :email, :pais_id, :estado, :cidade, :endereco_cep, :endereco_logradouro, :endereco_numero, :endereco_complemento, :profissao, :preferencia_contato, :imagem_perfil, :pessoa_tratamento_pronome_id, :inverter_pronome_tratamento)
    end

    def validar_usuario
      if usuario_atual.nil? || !(usuario_atual.corpo_clinico? || usuario_atual.secretaria?)
        render file: "#{Rails.root}/public/404.html", status: 404
      end
    end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/pessoas/_card.html.erb
<% if p != nil %>
  <% pro = p.profissional %>
  <%= link_to p, class: "pessoa-card" + " " + (p.feminino ? "feminino" : "masculino") + " " + "#{pro ? "profissional" : "usuario" }" do%>
    <div>
      <h2><%= p.nome_abreviado %><%#= p.feminino ? "(F)" : "(M)" %></h2>

      <h6>
        <%= if pro != nil then pro.profissional_funcao.funcao.upcase else p.profissao != nil ? p.profissao.upcase : "NA" end %>
      </h6>
      <!-- informações -->
      <p><%= p.data_nascimento ? p.render_data_nascimento : "Data Nasc. não informada" %> (<%= p.render_idade %>)</p>
      <% if p.cpf then %>
        <p><%= p.render_cpf %></p>
      <% end %>
        <p><%= p.email ? p.email : "Não definido" %></p>
        <p><%= (p.fone_cod_pais || p.fone_cod_area || p.fone_num) ? p.render_fone : "Não definido" %></p>
    </div>
  <% end %>
<% end %>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :nome_do_meio %>
    <%= form.text_field :nome_do_meio %>
  </div>

  <div class="field">
    <%= form.label :sobrenome %>
    <%= form.text_field :sobrenome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :fone_cod_pais %>
    <%= form.text_field :fone_cod_pais %>
  </div>

  <div class="field">
    <%= form.label :fone_cod_area %>
    <%= form.text_field :fone_cod_area %>
  </div>

  <div class="field">
    <%= form.label :fone_num %>
    <%= form.text_field :fone_num %>
  </div>

  <div class="field">
    <%= form.label :feminino, "Sexo" %>
    <%= form.select :feminino, [["Masculino", false], ["Feminino", true]] %>
  </div>

  <div class="field">
    <%= form.label :civil_estado_id, "Estado Civil" %>
    <%= form.select :civil_estado_id, CivilEstado.pluck(:estado, :id), include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :instrucao_grau_id, "Grau de instrução" %>
    <%= form.select :instrucao_grau_id, InstrucaoGrau.all.map {
      |instrucao_grau| [instrucao_grau.grau, instrucao_grau.id]
    } , include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :pais_id, "País" %>
    <%= form.select :pais_id, Pais.order(nome: :asc).pluck(:nome, :id), selected: @pessoa.pais_id || Pais.find_by(nome: "Brasil").id %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :endereco_cep %>
    <%= form.number_field :endereco_cep %>
  </div>

  <div class="field">
    <%= form.label :endereco_logradouro %>
    <%= form.text_field :endereco_logradouro %>
  </div>

  <div class="field">
    <%= form.label :endereco_numero %>
    <%= form.number_field :endereco_numero %>
  </div>

  <div class="field">
    <%= form.label :endereco_complemento %>
    <%= form.text_field :endereco_complemento %>
  </div>

  <div class="field">
    <%= form.label "Profissão" %>
    <%= form.text_field :profissao %>
  </div>

  <div class="field">
    <%= form.label "Preferência de contato" %>
    <%= form.text_field :preferencia_contato %>
  </div>

  <div class="field">
    <%= form.label "Pronome de tratamento" %>
    <%= form.select :pessoa_tratamento_pronome_id, PessoaTratamentoPronome.all.map { |pn| ["#{pn.pronome_masculino}/#{pn.pronome_feminino}", pn.id] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label "Inverter pronome" %>
    <%= form.check_box :inverter_pronome_tratamento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/devolutivas.html.erb
<h1>Devolutivas</h1>
<% @devolutivas.each do |devolutiva| %>
  <div class="devolutiva">
    <h2><%= render_data_brasil devolutiva.data %>
    <h3>Feedback Responsável</h3>
    <%== Kramdown::Document.new(devolutiva.feedback_responsavel).to_html %>
    <h3>Orientações do profissional</h3>
    <%== Kramdown::Document.new(devolutiva.orientacoes_profissional).to_html %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<%= titulo "Cadastros" %>
<p id="notice"><%= notice %></p>

<h1>Cadastros</h1>
<p>Quantidade de cadastros: <%= Pessoa.all.count %></p>

<%= link_to '+ cadastro', new_pessoa_path %>

<%= form_with url: pessoas_path, method: :get, local: true, data: { turbo_frame: 'pessoas' } do |form| %>
  <%= form.text_field :q, value: params[:q], placeholder: "Pesquisar por nome..." %>
  <%#= form.label :sexo %>
  <%#= form.select :sexo, [["Ambos", ''], ["Masculino", false], ["Feminino", true]] %>
  <%= form.submit "Pesquisar" %>
<% end %>
<!-- onde as pessoas ficam -->
<%== pagy_nav @pagy %>
<%= turbo_frame_tag 'pessoas' do %>
  <div class="pessoas-container">
  <% if !@pessoas.empty? %>
    <% @pessoas.each do |p| %>
      <%= render partial: 'card', locals: {p: p} %>
    <% end %>
  <% end %>
</div>
<% end %>

<br>

app/views/pessoas/informacoes_extras.html.erb
<% titulo "Informações extras de #{@pessoa.nome_abreviado}" %>
<h1><%= @pessoa.nome_completo %> - Informações Extras</h1>
<%= link_to "voltar", @pessoa %>
<%= link_to "+ informação extra", informacao_extra_new_pessoa_path %>
<% @pessoa.pessoa_extra_informacao.each do |ie| %>
  <p><%= ie.data %> <%= ie.meio.upcase %> (<%= link_to "editar", informacao_extra_edit_pessoa_path(extra_info_id: ie.id) %>)</p>
<% end %>

app/views/pessoas/new.html.erb
<%= titulo "Novas pessoas" %>
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<%= content_for titulo @pessoa.nome_abreviado %>
<p id="notice"><%= notice %></p>

<% pro = @pessoa.profissional %>

<div class="info-container">
    <div class="pessoa-container">
      <h2>
        <%= if !@pessoa.pessoa_tratamento_pronome.nil? then @pessoa.pronome_tratamento end %>
        <%= @pessoa.nome_completo %> <%= @pessoa.render_sexo_sigla %>
      </h2>
    
      <!-- se for profissional -->
      <% if !pro.nil? %>
        <div class="profissional">
          <% profunc = pro.profissional_funcao %>
          <p><%= profunc.funcao %> <%= pro.documento %></p>
          <%= link_to "Editar", edit_profissional_path, profissional: pro %>
        </div>
      <% end %>

      <p>
        CPF <%= @pessoa.render_cpf %>
      </p>

      <!-- informações de contato -->
      <div class="contato">
        <%= mail_to @pessoa.email %>
        <% if @pessoa.tem_telefone? %>
          <%= phone_to @pessoa.fone_cod_pais + @pessoa.render_fone_link, @pessoa.render_fone %>
          <%= link_to "ZAPZAP", "https://wa.me/#{@pessoa.render_fone_link}", target: :_blank %>
        <% end %>
      </div>

      <!-- dados pessoais -->
      <div class="dados-pessoais">
        <% if @pessoa.data_nascimento != nil %>
          <p><%= render_data_brasil @pessoa.data_nascimento %> (<%= @pessoa.render_idade %>)</p>
        <% end %>
        <%= @pessoa.instrucao_grau ? @pessoa.instrucao_grau.grau.upcase : "Não informado" %>
        <%= @pessoa.civil_estado ? @pessoa.civil_estado.estado : "Não informado" %>
      </div>

      <!-- dados de endereço -->
      <div class="endereco">
        <%= @pessoa.render_endereco %>
        <p><%= @pessoa.render_cidade_estado %></p>
        <p><%= @pessoa.pais.nome %></p>
      </div>
    </div>

    <%= link_to "Informações extras", informacoes_extras_pessoa_path(@pessoa) %>


    <div class="acompanhamentos">
      <!-- se é profissional -->
      <% if pro != nil %>
        <%= render 'profissionais/acompanhamentos-lista', profissional: pro %>
      <% end %>

      <!-- se é usuário -->
      <!-- últimos atendimentos ou próximos -->
      <% if !@pessoa.acompanhamentos.empty? %>
        <% if !@pessoa.atendimentos.where("DATEDIFF(data, CURRENT_DATE) > 0 OR (DATEDIFF(data, CURRENT_DATE) = 0 AND HOUR(horario) > HOUR(CURRENT_TIME))").empty? %>
          <div class="pessoa-proximos-atendimentos">
            <h3>Próximos atendimentos</h3>
              <ul>
                <% @pessoa.atendimentos_futuros.each do |at| %>
                  <li>
                    <% if usuario_atual.secretaria? || usuario_atual.profissional_id == at.profissional.id %>
                      <%= link_to at do %>
                        <%= at.acompanhamento_tipo.to_s.upcase %> - <%= render_data_brasil at.data %> às <%= render_hora_brasil at.horario %>
                      <% end %>
                    <% else %>
                      <%= at.acompanhamento_tipo.to_s.upcase %> - <%= render_data_brasil at.data %> às <%= render_hora_brasil at.horario %>
                    <% end %>
                    <%= link_to at.profissional do %>
                      (<%= at.profissional.nome_completo %>
                      <span style="font-size:.7em;"><%= at.profissional.documento %></span>)
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="pessoa-acompanhamentos">
          <h3>Acompanhamentos</h3>
          <ul>
            <% @pessoa.acompanhamentos.order(data_inicio: :desc).each do |a| %>
              <%= link_to a do %><li><%= a.render_info_para_pessoa %></li><% end %>
            <% end %>
          </ul>
        </div>
      <% end %>

      <!-- se é responsável -->
      <% if !@pessoa.acompanhamentos_responsavel.empty? %>
        <div class="pessoa-acompanhamentos-responsavel">
          <h3>Acompanhamentos pelos quais responde</h3>
          <% if @pessoa.acompanhamento_responsavel != nil %>
            <% @pessoa.acompanhamento_responsavel.order(data_inicio: :desc).each do |a| %>
              <%= link_to a do %><li><%= a.render_info_para_pessoa %></li><% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- se for usuário mostrar dados dos atendimentos -->
    <% if !@pessoa.atendimentos.empty? %>
      <%= render "resumo-caso", pessoa: @pessoa %>
    <% end %>
</div>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>