config/routes.rb
Rails.application.routes.draw do
  get 'financeiro/index'
  get 'financeiro/atendimento_valor'
  get 'financeiro/recebimento_pessoa'
  get 'financeiro/repasse_profissionais'

  # usuarios do sistema e sessão
  resources :usuarios
  resources :sessoes
  get 'criar_usuario', to: "usuarios#new", as: 'criar_usuario'
  get 'entrar', to: "sessoes#new", as: 'entrar'
  get 'sair', to: "sessoes#destroy", as: 'sair'

  # instrumentos
  resources :instrumentos
  resources :instrumento_relatos

  # anamneses
  resources :infantojuvenil_anamneses

  # biblioteca
  resources :biblioteca_obras
  resources :biblioteca_autores
  resources :biblioteca_tags
  
  scope :financeiro do
    resources :atendimento_valores
    resources :recebimentos
  end

  resources :profissionais do
    member do
      get :acompanhamentos
    end
  end
  resources :pessoa_devolutivas
  resources :laudos
  resources :crp_regioes
  resources :profissional_notas
  #resources :pessoas
  resources :pessoas, path: '/cadastros' do
    member do
      get :devolutivas, path: 'devolutivas'
      get :responsavel_devolutivas
      get :informacoes_extras
      get :informacao_extra_new, path: "informacoes_extras/new"
      get :informacao_extra_edit, path: "informacoes_extras/:extra_info_id"
    end
  end
  resources :paises
  resources :continentes
  resources :acompanhamentos do
    post :new_atendimento_proxima_semana, path: 'novo_atendimento_proxima_semana'
  end
  resources :atendimentos do
    member do
      post :reagendar_para_proxima_semana
      get :reagendar_para_proxima_semana
      post :create_atendimento_valor
    end
  end
  resources :relatos
  resources :pessoa_extra_informacoes

  resources :profissional_documento_modelos

  root to: "application#index"
  get '/financeiro', to: "financeiro#index"

  scope :admin do
    get '/', to: "admin#index", as: 'admin'
    AdminController.paths.each do |m|
      resources m.to_sym
      #get m.to_sym, to: "admin##{m}", as: m.to_s
    end
  end

  # rotas pdf
  get "/acompanhamentos/:id/detalhes", to: "acompanhamentos#caso_detalhes"
  get "/relatos/:id/pdf", to: "relatos#show_pdf"
  get "/pessoa_extra_informacoes/:id/pdf", to: "pessoa_extra_informacoes#show_pdf"

  # get pdf
  get "/pdf_download", to: "application#pdf_download"
  get "/pdf_preview", to: "application#pdf_preview"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pessoa_devolutiva.rb
class PessoaDevolutiva < ApplicationRecord
  belongs_to :pessoa
  belongs_to :profissional
  belongs_to :responsavel, class_name: "Pessoa", foreign_key: :pessoa_responsavel_id
end

app/controllers/pessoa_devolutivas_controller.rb
class PessoaDevolutivasController < ApplicationController
  before_action :set_pessoa_devolutiva, only: %i[ show edit update destroy ]

  # GET /pessoa_devolutivas or /pessoa_devolutivas.json
  def index
    @pessoa_devolutivas = pessoaDevolutiva.all
  end

  # GET /pessoa_devolutivas/1 or /pessoa_devolutivas/1.json
  def show
  end

  # GET /pessoa_devolutivas/new
  def new
    @pessoa_devolutiva = PessoaDevolutiva.new
  end

  # GET /pessoa_devolutivas/1/edit
  def edit
  end

  # POST /pessoa_devolutivas or /pessoa_devolutivas.json
  def create
    @pessoa_devolutiva = PessoaDevolutiva.new(pessoa_devolutiva_params)

    respond_to do |format|
      if @pessoa_devolutiva.save
        format.html { redirect_to pessoa_devolutiva_url(@pessoa_devolutiva), notice: "pessoa devolutiva was successfully created." }
        format.json { render :show, status: :created, location: @pessoa_devolutiva }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pessoa_devolutiva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoa_devolutivas/1 or /pessoa_devolutivas/1.json
  def update
    respond_to do |format|
      if @pessoa_devolutiva.update(pessoa_devolutiva_params)
        format.html { redirect_to pessoa_devolutiva_url(@pessoa_devolutiva), notice: "pessoa devolutiva was successfully updated." }
        format.json { render :show, status: :ok, location: @pessoa_devolutiva }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pessoa_devolutiva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoa_devolutivas/1 or /pessoa_devolutivas/1.json
  def destroy
    @pessoa_devolutiva.destroy

    respond_to do |format|
      format.html { redirect_to pessoa_devolutivas_url, notice: "pessoa devolutiva was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa_devolutiva
      @pessoa_devolutiva = PessoaDevolutiva.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_devolutiva_params
      params.require(:pessoa_devolutiva).permit(:pessoa_id, :pessoa_responsavel_id, :profissional_id, :data, :feedback_responsavel, :orientacoes_profissional)
    end
end

app/views/pessoa_devolutivas/_form.html.erb
<%= form_with(model: usuario_devolutiva, local: true) do |form| %>
  <% if usuario_devolutiva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario_devolutiva.errors.count, "error") %> prohibited this usuario_devolutiva from being saved:</h2>

      <ul>
      <% usuario_devolutiva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= form.label :usuario_responsavel_id %>
    <%= form.number_field :usuario_responsavel_id %>
  </div>

  <div class="field">
    <%= form.label :profissional_id %>
    <%= form.text_field :profissional_id %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :feedback_responsavel %>
    <%= form.text_area :feedback_responsavel %>
  </div>

  <div class="field">
    <%= form.label :orientacoes_profissional %>
    <%= form.text_area :orientacoes_profissional %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoa_devolutivas/edit.html.erb
<h1>Editing Usuario Devolutiva</h1>

<%= render 'form', usuario_devolutiva: @usuario_devolutiva %>

<%= link_to 'Show', @usuario_devolutiva %> |
<%= link_to 'Back', usuario_devolutivas_path %>

app/views/pessoa_devolutivas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuario Devolutivas</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Usuario responsavel</th>
      <th>Profissional</th>
      <th>Data</th>
      <th>Feedback responsavel</th>
      <th>Orientacoes profissional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuario_devolutivas.each do |usuario_devolutiva| %>
      <tr>
        <td><%= usuario_devolutiva.usuario %></td>
        <td><%= usuario_devolutiva.usuario_responsavel_id %></td>
        <td><%= usuario_devolutiva.profissional %></td>
        <td><%= usuario_devolutiva.data %></td>
        <td><%= usuario_devolutiva.feedback_responsavel %></td>
        <td><%= usuario_devolutiva.orientacoes_profissional %></td>
        <td><%= link_to 'Show', usuario_devolutiva %></td>
        <td><%= link_to 'Edit', edit_usuario_devolutiva_path(usuario_devolutiva) %></td>
        <td><%= link_to 'Destroy', usuario_devolutiva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario Devolutiva', new_usuario_devolutiva_path %>

app/views/pessoa_devolutivas/new.html.erb
<h1>New Usuario Devolutiva</h1>

<%= render 'form', usuario_devolutiva: @usuario_devolutiva %>

<%= link_to 'Back', usuario_devolutivas_path %>

app/views/pessoa_devolutivas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @usuario_devolutiva.usuario %>
</p>

<p>
  <strong>Usuario responsavel:</strong>
  <%= @usuario_devolutiva.usuario_responsavel_id %>
</p>

<p>
  <strong>Profissional:</strong>
  <%= @usuario_devolutiva.profissional %>
</p>

<p>
  <strong>Data:</strong>
  <%= @usuario_devolutiva.data %>
</p>

<p>
  <strong>Feedback responsavel:</strong>
  <%= @usuario_devolutiva.feedback_responsavel %>
</p>

<p>
  <strong>Orientacoes profissional:</strong>
  <%= @usuario_devolutiva.orientacoes_profissional %>
</p>

<%= link_to 'Edit', edit_usuario_devolutiva_path(@usuario_devolutiva) %> |
<%= link_to 'Back', usuario_devolutivas_path %>