config/routes.rb
Rails.application.routes.draw do
  get 'financeiro/index'
  get 'financeiro/atendimento_valor'
  get 'financeiro/recebimento_pessoa'
  get 'financeiro/repasse_profissionais'

  # usuarios do sistema e sessão
  resources :usuarios
  resources :sessoes
  get 'criar_usuario', to: "usuarios#new", as: 'criar_usuario'
  get 'entrar', to: "sessoes#new", as: 'entrar'
  get 'sair', to: "sessoes#destroy", as: 'sair'

  # instrumentos
  resources :instrumentos
  resources :instrumento_relatos

  # anamneses
  resources :infantojuvenil_anamneses

  # biblioteca
  resources :biblioteca_obras
  resources :biblioteca_autores
  resources :biblioteca_tags
  
  scope :financeiro do
    resources :atendimento_valores
    resources :recebimentos
  end

  resources :profissionais do
    member do
      get :acompanhamentos
    end
  end
  resources :pessoa_devolutivas
  resources :laudos
  resources :crp_regioes
  resources :profissional_notas
  #resources :pessoas
  resources :pessoas, path: '/cadastros' do
    member do
      get :devolutivas, path: 'devolutivas'
      get :responsavel_devolutivas
      get :informacoes_extras
      get :informacao_extra_new, path: "informacoes_extras/new"
      get :informacao_extra_edit, path: "informacoes_extras/:extra_info_id"
    end
  end
  resources :paises
  resources :continentes
  resources :acompanhamentos do
    post :new_atendimento_proxima_semana, path: 'novo_atendimento_proxima_semana'
  end
  resources :atendimentos do
    member do
      post :reagendar_para_proxima_semana
      get :reagendar_para_proxima_semana
      post :create_atendimento_valor
    end
  end
  resources :relatos
  resources :pessoa_extra_informacoes

  resources :profissional_documento_modelos

  root to: "application#index"
  get '/financeiro', to: "financeiro#index"

  scope :admin do
    get '/', to: "admin#index", as: 'admin'
    AdminController.paths.each do |m|
      resources m.to_sym
      #get m.to_sym, to: "admin##{m}", as: m.to_s
    end
  end

  # rotas pdf
  get "/acompanhamentos/:id/detalhes", to: "acompanhamentos#caso_detalhes"
  get "/relatos/:id/pdf", to: "relatos#show_pdf"
  get "/pessoa_extra_informacoes/:id/pdf", to: "pessoa_extra_informacoes#show_pdf"

  # get pdf
  get "/pdf_download", to: "application#pdf_download"
  get "/pdf_preview", to: "application#pdf_preview"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/financeiro_controller.rb
class FinanceiroController < ApplicationController
  before_action :validar_usuario

  def index
    if usuario_atual.financeiro?
      @recebimentos = Recebimento.all.order(data: :desc).first 10
      @atendimento_valores = AtendimentoValor.joins("JOIN atendimentos ON atendimento_valores.atendimento_id = atendimentos.id").where(atendimentos: {data: [..Date.today]}).order(data: :desc, horario: :desc).first 10
      @profissional_financeiro_repasses = ProfissionalFinanceiroRepasse.order(data: :desc).first 10
      @acompanhamentos = Acompanhamento.where(data_final: nil, acompanhamento_finalizacao_motivo: nil)
      @profissionais = Profissional.all
    elsif usuario_atual.corpo_clinico?
      @recebimentos = usuario_atual.profissional.recebimentos.order(data: :desc).first 10
      @atendimento_valores = usuario_atual.profissional.atendimento_valores.joins(:atendimento).where("atendimentos.data" => [..Date.today]).order("atendimentos.data" => :desc, "atendimentos.horario" => :desc).first 10
      @profissional_financeiro_repasses = usuario_atual.profissional.repasses.order(data: :desc).first 10
      @profissionais = Profissional.where(id: usuario_atual.profissional.id)
      @acompanhamentos = usuario_atual.profissional.acompanhamentos
    end
  end

  def atendimento_valor
  end

  def recebimento_usuario
  end

  def repasse_profissionais
  end

  private

  def validar_usuario
    if usuario_atual.nil? || !(usuario_atual.corpo_clinico? || usuario_atual.financeiro?)
      render file: "#{Rails.root}/public/404.html", status: 404
    end
  end
end

app/helpers/financeiro_helper.rb
module FinanceiroHelper
end

app/views/financeiro/_tabela-gastos.html.erb
<table class="tabela-gastos">
  <thead>
    <caption>Gastos</caption>
    <tr>
      <th>Tipo</th>
      <th>Valor da despesa</th>
      <th>Valor pago</th>
      <th>Valor restante</th>
    </tr>
  </thead>
  <tbody>
    <!-- por enquanto é placeholder -->
    <% valor_1 = rand(4300..15900) %>
    <% valor_1_1 = rand(valor_1) %>
    <% valor_2 = rand(1276..35493) %>
    <% valor_2_1 = rand(valor_2) %>
    <% valor_3 = rand(1270..80767) %>
    <% valor_3_1 = rand(valor_3) %>
    <% gastos = [
    ["Sabão", valor_1, valor_1_1],
    ["Hipopótamo", valor_2, valor_2_1],
    ["Rosa", valor_3, valor_3_1]
    ] %>
  <% soma = ["", 0, 0] %>
  <% pagar = 0 %>
    <% gastos.each do |despesa| %>
      <!-- soma placeholder -->
      <% soma[1] += despesa[1] %>
      <% soma[2] += despesa[2] %>
      <% pagar += despesa[1] - despesa[2] %>
      <tr>
        <td><%= despesa[0] %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos despesa[1] %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos despesa[2] %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos(despesa[1] - despesa[2]) %></td>
      </tr>
    <% end %>
    <tr>
      <td class="resultado">Total</td>
      <td class="dinheiro resultado"><%= render_dinheiro_centavos soma[1] %></td>
      <td class="dinheiro resultado"><%= render_dinheiro_centavos soma[2] %></td>
      <td class="dinheiro resultado"><%= render_dinheiro_centavos pagar %></td>
    </tr>
  </tbody>
</table>

app/views/financeiro/_tabela-repasses.html.erb
<table class="tabela-repasses">
  <caption>Repasses aos profissionais</caption>
  <thead>
    <tr>
      <th>Profissional</th>
      <th>Repasses mês passado</th>
      <th>Repasses deste mês</th>
      <th>Valor faltante</th>
    </tr>
  </thead>
  <tbody>
    <% mes_passado = [(Date.today - 1.month).beginning_of_month..(Date.today - 1.month).end_of_month] %>
    <% mes_atual = [Date.today.beginning_of_month..Date.today.end_of_month] %>

    <% profissionais.all.each do |profissional| %>
      <tr>
        <td><%= profissional.nome_abreviado %> - <%= profissional.documento %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.repasses.where(data: mes_passado).sum(:valor) %> (<%= profissional.repasses.where(data: mes_passado).count %> repasses)</td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.repasses.where(data: mes_atual).sum(:valor) %> (<%= profissional.repasses.where(data: mes_atual).count %> repasses)</td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.recebimentos.sum(:valor) - profissional.repasses.sum(:valor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/financeiro/_tabela-resumo.html.erb
<table class="tabela-valores">
  <caption>Resumo de valores</caption>
  <thead>
    <tr>
      <th rowspan=2>Função</th>
      <th rowspan=2>Profissional</th>
      <th rowspan=2>Acompanhamentos</th>
      <th rowspan=2>Valor mensal aprox.</th>
      <th colspan=2>Valores de atendimentos</th>
      <th colspan=2>Recebimentos</th>
    </tr>
    <tr>
      <th>Mês passado</th>
      <th>Mês atual</th>
      <th>Mês passado</th>
      <th>Mês atual</th>
    </tr>
  </thead>
  <tbody>
    <% mes_passado = [(Date.today - 1.month).beginning_of_month..(Date.today - 1.month).end_of_month] %>
    <% mes_atual = [Date.today.beginning_of_month..Date.today.end_of_month] %>
    <% @profissionais.each do |profissional| %>
      <tr>
        <td><%= profissional.funcao %></td>
        <td><%= profissional.nome_abreviado %> - <%= profissional.documento %></td>
        <td style="text-align:right;"><%= profissional.acompanhamentos_em_andamento.count %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.acompanhamentos_em_andamento.sum("valor_atual * sessoes_atuais") %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.atendimento_valores.where("atendimentos.data" => mes_passado).sum(:valor) %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.atendimento_valores.where("atendimentos.data" => mes_atual).sum(:valor) %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.recebimentos.where(data: mes_passado).sum(:valor) %></td>
        <td class="dinheiro"><%= render_dinheiro_centavos profissional.recebimentos.where(data: mes_atual).sum(:valor) %></td>
      </tr>
    <% end %>
    <% if usuario_atual.financeiro? %>
      <tr>
        <% total_mes_passado = AtendimentoValor.joins("JOIN atendimentos ON atendimento_valores.atendimento_id = atendimentos.id").where(atendimentos: {data: mes_passado}).sum(:valor) %>
        <% total_mes_atual = AtendimentoValor.joins("JOIN atendimentos ON atendimento_valores.atendimento_id = atendimentos.id").where(atendimentos: {data: mes_atual}).sum(:valor) %>
        <% total_recebimentos_mes_passado = Recebimento.where(data: mes_passado).sum(:valor) %>
        <% total_recebimentos_mes_atual = Recebimento.where(data: mes_atual).sum(:valor) %>
        <td colspan="2" class="resultado">Total</td>
        <td class="resultado"><%= @acompanhamentos.count %></td>
        <td class="resultado"><%= render_dinheiro_centavos @acompanhamentos.sum("valor_atual * sessoes_atuais") %></td>
        <td class="resultado"><%= render_dinheiro_centavos total_mes_passado %></td>
        <td class="resultado"><%= render_dinheiro_centavos total_mes_atual %></td>
        <td class="resultado"><%= render_dinheiro_centavos total_recebimentos_mes_passado %></td>
        <td class="resultado"><%= render_dinheiro_centavos total_recebimentos_mes_atual %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/financeiro/atendimento_valor.html.erb
<h1>Financeiro#atendimento_valor</h1>
<p>Find me in app/views/financeiro/atendimento_valor.html.erb</p>

app/views/financeiro/index.html.erb
<% titulo "Financeiro" %>
<h1>Financeiro</h1>

<!-- tabela de profissionais e o quanto ganham no mês -->
<div class="grid-2">
  <div class="financeiro-tabelas">
    <%= render "tabela-resumo", profissionais: @profissionais %>
    <br />
    <%= render "tabela-repasses", profissionais: @profissionais %>
    <br />
    <% if usuario_atual.financeiro? %>
      <%= render "tabela-gastos" %>
    <% end %>
  </div>
  <div class="grid-3">
    <div>
      <h2>Últimos Recebimentos</h2>
      <div class="recebimentos-container">
        <% @recebimentos.each do |recebimento| %>
          <p>
            <%= render_data_brasil recebimento.data %> -
            <%= recebimento.pagante.nome_completo %>
            <%= render_dinheiro_centavos recebimento.valor %>
            <%= recebimento.modalidade || "Meio desconhecido" %>
          </p>
        <% end %>
        <%= link_to "ver mais", recebimentos_path %>
      </div>
    </div>

    <div>
      <h2>Últimos atendimentos</h2>
      <div class="atendimento-valores-container">
        <% @atendimento_valores.each do |atendimento_valor| %>
          <p>
            <strong><%= render_dinheiro_centavos atendimento_valor.valor %></strong>
            <%= render_data_brasil atendimento_valor.data %>
            <%= render_hora_brasil atendimento_valor.horario %>
            <%= atendimento_valor.pessoa.nome_completo %>
            <%= atendimento_valor.atendimento.tipo.upcase %>
            <%= atendimento_valor.atendimento.modalidade %>
          </p>
        <% end %>
        <%= link_to "mais...", atendimento_valores_path %>
      </div>
    </div>

    <div>
      <h2>Últimos repasses</h2>
      <% @profissional_financeiro_repasses.each do |repasse| %>
        <p>
          <%= render_data_brasil repasse.data %>
          <%= repasse.profissional.nome_abreviado %>
          <%= repasse.profissional.documento %>
          <%= render_dinheiro_centavos repasse.valor %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/financeiro/recebimento_usuario.html.erb
<h1>Financeiro#recebimento_usuario</h1>
<p>Find me in app/views/financeiro/recebimento_usuario.html.erb</p>

app/views/financeiro/repasse_profissionais.html.erb
<h1>Financeiro#repasse_profissionais</h1>
<p>Find me in app/views/financeiro/repasse_profissionais.html.erb</p>